### ISSUE TITLE
源码包

### ISSUE THREAD

**Issue by laolangs** [xnx3/wangmarket#1]
源码生成的网页是乱码
![image](https://user-images.githubusercontent.com/18112193/35344959-57e0555a-0169-11e8-854d-91410e2bdaa4.png)
但是管理页面编辑的时候是正常的
![image](https://user-images.githubusercontent.com/18112193/35345013-77aa0d04-0169-11e8-8510-5778829be05d.png)

**Comment by xnx3** [comment]
多谢提醒！再Windows上测试发现了这个问题，下一个版本修复。可能这周末会发布已修复的新版本

**Comment by xnx3** [comment]
不过在Linux、或Mac OS 会正常生成网站，可先体验一下Linux上的效果，待发布新版修复后再上Windows进行体验或应用

**Comment by laolangs** [comment]
ok   谢谢，打算周末学习一下
